### ISSUE TITLE
Executing named workflows missing

### ISSUE THREAD

**Issue by websupplements** [AlexaCRM/php-crm-toolkit#100]
There is no functionality to execute named workflows in the library. Below is a sample code for doing the same in .NET.

```
try
{
  // Create an ExecuteWorkflow request.
  ExecuteWorkflowRequest request = new ExecuteWorkflowRequest();

  //Assign the ID of the workflow you want to execute to the request. 
  request.WorkflowId = new Guid("xxxxxx-xxx-xxx-xxxx-xxxxxx");

  //Assign the ID of the entity to execute the workflow on to the request.
  request.EntityId = accountGUID;

  // Execute the workflow.
  ExecuteWorkflowResponse response = (ExecuteWorkflowResponse)service.Execute(request);
}
```

**Comment by georged** [comment]
Hi @websupplements 

we have no current plans to add this functionality to the toolkit, mostly because SOAP API has been deprecated. Moving forward, https://github.com/AlexaCRM/dynamics-webapi-toolkit is the one to use.

Having said that, we will definitely consider a pull request for the feature.

Thanks
