### ISSUE TITLE
Strange error: InvalidSecurityException: An error occurred when verifying security for the message

### ISSUE THREAD

**Issue by dantedantas** [AlexaCRM/php-crm-toolkit#104]
Hello All,

I have a strange issue.
Yesterday my system worked fine. Today it becomes an error:

`**Fatal error:** Uncaught AlexaCRM\CRMToolkit\InvalidSecurityException: An error occurred when verifying security for the message. in C:\Tools\xampp\htdocs\incidentreport\vendor\alexacrm\php-crm-toolkit\src\Client.php:1157 Stack trace: #0 C:\Tools\xampp\htdocs\incidentreport\vendor\alexacrm\php-crm-toolkit\src\Client.php(2017): AlexaCRM\CRMToolkit\Client->getSoapResponse('https://disco.c...', '<s:Envelope xml...') #1 C:\Tools\xampp\htdocs\incidentreport\vendor\alexacrm\php-crm-toolkit\src\Client.php(897): AlexaCRM\CRMToolkit\Client->attemptSoapResponse('discovery', Object(Closure)) #2 C:\Tools\xampp\htdocs\incidentreport\vendor\alexacrm\php-crm-toolkit\src\Client.php(945): AlexaCRM\CRMToolkit\Client->retrieveOrganizations() #3 C:\Tools\xampp\htdocs\incidentreport\vendor\alexacrm\php-crm-toolkit\src\Client.php(176): AlexaCRM\CRMToolkit\Client->retrieveOrganization('https://smartst...') #4 C:\Tools\xampp\htdocs\incidentreport\odataconnector.php(18): AlexaCRM\CRMToolkit\Client->__construct(Object(AlexaCRM\CRMToolkit\Settings)) # in C:\Tools\xampp\htdocs\incidentreport\vendor\alexacrm\php-crm-toolkit\src\Client.php on line 1157`

Nothing was changed. Could someone help me to identify the reason for this issue and how to solve it?

Thank you in advance.

BR,
Dante

**Comment by dantedantas** [comment]
Hello, please, could someone help me?

**Comment by georged** [comment]
@dantedantas can you set and capture debug logs (on About tab), then email your logs to support@alexacrm.com. I suspect that you've had changes done on your Active Directory (e.g. enabled MFA or disabled legacy protocols) that break the sign in process

**Comment by dantedantas** [comment]
Hi George,

Thank you for the feedback.
Sorry my question, but how could I set the debug logs? And where will I
find the logs?

Thank you.

Em ter, 26 de mai de 2020 02:47, George Doubinski <notifications@github.com>
escreveu:

**Comment by dantedantas** [comment]
Hi @georged,
thank you for your attention. I dropped an email to you. 
Additional information: We hade a "service update" last Friday. (The service update is version 9.1.0.17401)

https://docs.microsoft.com/en-gb/business-applications-release-notes/dynamics/released-versions/weekly-releases/update174

Thank you.

--

**Comment by georged** [comment]
Hi @dantedantas 

it's not php log I was talking about. Our [client constructor](https://github.com/AlexaCRM/php-crm-toolkit/blob/15c8aecde18a412b35d4fa7769d670efb808c0b1/src/Client.php#L125) takes LoggerInterface. You can drop in your own logger, set debug level and capture additional information about why connection is failing.

`use AlexaCRM\CRMToolkit\Client;
use AlexaCRM\CRMToolkit\Settings;
use Monolog\Logger;

require_once 'vendor/autoload.php';
$log = new \Monolog\Logger( 'whatever' );
$log->pushHandler(new StreamHandler('php://stdout', Logger::DEBUG));
$clientOptions  = include( 'config.php' );
$clientSettings = new Settings( $clientOptions );
$client         = new Client( $clientSettings, null, $log );
`


My guess? It's because someone disabled legacy protocols in Azure AD.
Thanks
George
