### ISSUE TITLE
How to retrieve id from this data  

### ISSUE THREAD

**Issue by Tameem-Ahmad-com** [AlexaCRM/php-crm-toolkit#112]
```
AlexaCRM\CRMToolkit\Entity\EntityReference {#570 ▼
  #entityLogicalName: "account"
  #entityID: "b66de938-0320-e711-810b-c4346bad3418"
  #displayName: "Energy Aware"
  #keyAttributes: []
}
```

**Comment by georged** [comment]
Record ID? It's `entityID` property.
@Tameem-Ahmad-com I would recommend reading Microsoft documentation regarding relevant data types like EntityReference

**Comment by Tameem-Ahmad-com** [comment]
#entityID: "b66de938-0320-e711-810b-c4346bad3418" i want to get this using your package

**Comment by georged** [comment]
@Tameem-Ahmad-com 
I really don't understand what the problem is.
If you have an entity reference, e.g. `$entityReference` then `$entityReference.entityID`  will provide the id value you're after. Please include a fragment of your code where you're getting the EntityReference to help us understand what you're after
