### ISSUE TITLE
App authentication

### ISSUE THREAD

**Issue by moerg** [AlexaCRM/php-crm-toolkit#20]
Is there a way to authenticate as an app using administrator consent has shown below with your toolkit?

I would like to authenticate one time and keep the refresh token for further use to avoid user authentication as explained in your examples.

Thank you for any follow-up.

![image 40](https://cloud.githubusercontent.com/assets/10135983/24267724/a2b164ea-0fe1-11e7-915f-f1ebeb678d9a.png)

**Comment by georged** [comment]
Hi @moerg 

what you're looking for is a consent which is part of OAuth flow. I'm not 100% sure that I understand your scenario though. Typically, one would register an app in Azure AD and then use clientid and secret to do server-to-server authentication and that flow may require consent. Is that your scenario? We don't support it yet but it's on a roadmap. Since support for Azure AD S2S was added not so long ago, we didn't have a chance to add it yet.

Another possible scenario is accessing CRM on behalf of CRM users, i.e. users would go through the Azure AD logon and then the web site would access CRM on their behalf. We do partially support this scenario in our WordPress plugin but I don't think it's part of the php toolkit.

Let us know what implementation you have in mind.

Thanks
George

**Comment by vicentor** [comment]
Hey there! I'm pretty sure he was referring to server-to-server.

We've made a custom script that does that OAuth admin consent flow, we may share it if someone can convert it to proper code/this Repo's standards.

As far as I know, new Apps have to be created in [https://apps.dev.microsoft.com/Landing?ru=https%3a%2f%2fapps.dev.microsoft.com%2f](url) instead of AD to fully grasp the v2 flow including the "Admin consent" one.

**Comment by moerg** [comment]
Hi @georged, as @vicentor said, I was refrring to S2S authentication with admin consent.

That'd be great to support that feature soon with @vicentor code.

Thank you for your follow-up!

**Comment by georged** [comment]
@vicentor 
contribution would be great! If you're uncomfortable with forking the project, just send us your code and we'll see what we can do about incorporating it asap. The URL for apps you referred to is not for S2S applications, it's for registering apps to allow using Microsoft Account to login. Federation with Microsoft Account (or any other provider like Facebook, etc) is on a roadmap but we're planning to do that using Azure AD B2C feature.

@moerg 
S2S authentication is quite high on our list. I don't know the exact timeframe but, we're considering adding S2S flow without web api and, if that's going to work for us, then we should be up and running with S2S very soon. 

Cheers
George

**Comment by vicentor** [comment]
Here is a stand-alone snippet that we got working. You can put it on a Web server, edit the AA, BB, CC, DD, EE and run it. The generated links are where the user should be redirected to obtain consent and permissions.

	<?php
	$tenant = "AA";

	// From: https://apps.dev.microsoft.com/#/application/333a7cc5-dc75-4947-8e67-ce0a7fd4eef2
	$client_id = "BB";
	$client_secret = "CC";

	$resource = urlencode("https://DD.crm.dynamics.com");
	$redirect_uri = urlencode("EE");
	$scope = urlencode("openid offline_access");

	// 1. Admin consent (the user must be redirected to this URL to give consent)
	$url_admin_consent = "https://login.microsoftonline.com/$tenant/adminconsent?client_id=$client_id&redirect_uri=$redirect_uri";
	echo "1. Admin consent<br><a href=\"$url_admin_consent\" target=\"_blank\">$url_admin_consent</a><br><br>";

	// 2. Gaining auth code
	$url_auth_code = "https://login.microsoftonline.com/$tenant/oauth2/v2.0/authorize?client_id=$client_id&response_type=code&redirect_uri=$redirect_uri&response_mode=query&scope=$scope";
	echo "2. Auth<br><a href=\"$url_auth_code\" target=\"_blank\">$url_auth_code</a><br><br>";

	if(isset($_GET['code'])){
		// It changes every hour
		$code = urldecode($_GET['code']);

		// 3. Gaining access token (this endpoint only receives POSTs)
		$data_raw_token = "grant_type=authorization_code&client_id=$client_id&code=$code&redirect_uri=$redirect_uri&client_secret=$client_secret"; // Removed: &resource=$resource

		$ch = curl_init();
		curl_setopt_array($ch, array(
			CURLOPT_URL => "https://login.microsoftonline.com/$tenant/oauth2/v2.0/token",
			CURLOPT_FRESH_CONNECT => true,
			CURLOPT_RETURNTRANSFER => true,
			CURLOPT_POST => true,
			CURLOPT_HTTPHEADER => array(
				"Content-Type: application/x-www-form-urlencoded",
				"Content-Length: ".strlen($data_raw_token),
				"OData-MaxVersion: 4.0",
				"OData-Version: 4.0",
				"Cache-Control: no-cache"
			),
			CURLOPT_POSTFIELDS => $data_raw_token
		));
		$response = curl_exec($ch);

		echo "Sent:<br>".$data_raw_token."<br><br>";
		echo "Received:<br>";
		var_dump($response);
		echo '<br><br>';
	}
	exit;

**Comment by georged** [comment]
Hi @vicentor ,

thanks a lot for the code! Looks good, we'll see what we can do about incorporating it. I'm still nto sure I understand how https://apps.dev.microsoft.com comes into the picture. Application id, client id, and client secret in S2S all come from the app registration information in Azure AD, not Microsoft dev account. That's where web app is also granted permissions to access CRM on behalf of the users. Were you able to get it all working with the apps registered at https://apps.dev.microsoft.com?!

Cheers
George

**Comment by vicentor** [comment]
Hi @georged,
Yes, we initially had an App in Azure AD and it was working fine, but we couldn't get a full admin consent to work. After a while, we found out that Azure AD is the "normal"(/right?) way to manage the Apps, but that the Application Registration Portal is currently undergoing a "preview" for the v2 endpoints. This is why gaining a S2S full admin consent is only possible through these Apps as far as I know.

[http://stackoverflow.com/questions/32028343/office365-api-authentication-azure-vs-application-registration-portal](http://stackoverflow.com/questions/32028343/office365-api-authentication-azure-vs-application-registration-portal)

Be aware that we have a lot to learn ourselves, you most likely know more than us at this point. :)

Kind regards

**Comment by georged** [comment]
Hi @vicentor 

thanks for the link. It gets stranger and stranger :)
 
The only thing I noticed recently is that granting app permissions wasn't working in the Azure portal but the old Azure portal was working just fine for the purpose. Otherwise I'm not aware of any issues with the admin consent (not sure what you're referring to by qualifying it as "full").

We'll do some testing to be sure.

Cheers
George

**Comment by Mutnat** [comment]
Okay, I'm definitely confused.  If you've got a PHP web application that needs to connect to Dynamics 365 Online (v9 in this case), using a pre-defined O365 username and password, headlessly, and interact with the org service, will the toolkit do this today?  The code shown on the readme page suggests to me that setting the right $options values with the right org URL, username (email), password, and "OnlineFederation" would be sufficient.  Am I wrong?

**Comment by Mutnat** [comment]
Thanks georged.  I will pass this toolkit info on to the PHP developer I am working with.  I appreciate your quick reply.

**Comment by georged** [comment]
S2S has been implemented in https://github.com/AlexaCRM/dynamics-webapi-toolkit
