### ISSUE TITLE
Success Response too slow after creating lead

### ISSUE THREAD

**Issue by sdangol** [AlexaCRM/php-crm-toolkit#39]
I used the php-crm-toolkit for creating new leads in the CRM. It was integrated in my ajax contact form. Everything is working fine. Data is sent to the CRM but the only problem is that it takes too long for the success response. It takes around 40 seconds to complete. Should it be this slow?? Are there any ways to speed this ?
![screenshot from 2017-11-02 17-55-20](https://user-images.githubusercontent.com/22979656/32334259-1f3817da-c012-11e7-86e4-85ace44871c0.png)

**Comment by georged** [comment]
@sdangol this is not normal for a simple lead creation. The latency could be at play but not to the tune of 40 seconds. Can you please share the code you use to create the lead? Also, how long does it take to create a lead record in CRM UI using a form with the same fields as your online form. The delay could be caused by the code on the server-side, for example.

**Comment by wizardist** [comment]
Hi @sdangol. The reason why your case may be that slow is because you haven't employed caching. The toolkit uses caching for two things: storing authentication tokens and WSDLs, as well as storing your CRM entity metadata.

To speed things up, you need to implement two things: `CacheInterface` to store the authentication token from AAD/ADFS, and `StorageInterface` to store your CRM metadata.

Then you need to pass an instance of `CacheInterface` when you create the client instance (refer to `Client::__construct()`;

After you have an instance of `Client`, call this:

```
MetadataCollection::instance()->setStorage( $storage );
```

In this example, `$storage` is an object implementing `StorageInterface`. You also should to implement `StorageInterface::cleanup()` in order to clean up metadata cache from time to time to keep up with metadata changes in your CRM, if any.
