### ISSUE TITLE
retrieve the contact record by its e-mail (emailaddress1)

### ISSUE THREAD

**Issue by Addviso** [AlexaCRM/php-crm-toolkit#66]
Hello,

Just started to use use your php wrapper, whiwh is cool.
Il need to retrieve one contact by it's email, and your example in cli-contact.php doesn't work.
I've been said that you only can retrieve a contact by its GUID which is working in your example,  otherwise, you have to use RetrieveMultiple. 

If I've well understood the mechanism, this implies to use retrieveSingle with a queryXML, is that right?

Thanks.
Scott

**Comment by georged** [comment]
Hi Scott,

we do support retrieve by alternate keys, I believe so, if your email field is defined as alternate key then it is possible. Otherwise, correct, `RetrieveMultiple` with fetchxml would be your only option because we don't know how many customers are going to match the address you provide.

HTH
George
