### ISSUE TITLE
"faultcode":"-2147220970","faultstring":"An unexpected error occurred.","faultactor":null,"detail":null,"faultname":null,"headerfault":null

### ISSUE THREAD

**Issue by babininja** [AlexaCRM/php-crm-toolkit#69]
Hi, i want to update this entity `dynamicpropertyinstance`. i get it with id and does my changes but when i call update it gives me this error ```"faultcode":"-2147220970","faultstring":"An unexpected error occurred.","faultactor":null,"detail":null,"faultname":null,"headerfault":null```

**Comment by georged** [comment]
@babininja 

this error is generated by Dynamics, and it's not something that toolkit has any control over. There are plenty of posts on the web referring to this fault number, I suggest you go through those trying to resolve the problem. I would suggest tracing the request with something like Postman to figure out what the problem is.

HTH
George
