### ISSUE TITLE
(HELP) How to access an AliasedValue

### ISSUE THREAD

**Issue by dantedantas** [AlexaCRM/php-crm-toolkit#89]
Dear All,

I have the FetchXML script below:

```
"<fetch mapping='logical' distinct='false' aggregate='true' >
<entity name='incident' >
    <attribute name='ownerid' alias='SUPPName' groupby='true' />
    <attribute name='prioritycode' alias='prioritycode' groupby='true' />
    <attribute name='statuscode' alias='statuscode' groupby='true' />
    <attribute name='ownerid' alias='ownerid_count' aggregate='countcolumn' />
    <filter type='and' >
        <condition attribute='createdon' operator='this-week' />
    </filter>
</entity>
</fetch>"
```

Please, could you tell me how to list the AliasedValue on PHP?
I would like to list those fields (alias) below:

- SUPPName_owneridname (or SUPPName_owneridyominame)

- statuscode_statuscodename

My code in PHP:

```
foreach ($sysaccounts->Entities as $sysaccount) {
  echo "$sysaccount->SUPPName_SUPPNamename - $sysaccount->statuscode_statuscodename - $sysaccount->prioritycode - $sysaccount->ownerid_count</br>";
}
```

I tried to find a solution without success.
Thank you for your attention and help.

Best regards,

Dante Dantas

**Comment by dantedantas** [comment]
I did some changes and now I can see the names, but 1 field I still do not have access to the name. After change the name alias, I am able to see the ID but I am not able to see the name. In opposite, the field 'ownerid', I changed the alias (as you may see), and now I can list the name. I do not understand why doesn't work to both fields.

![image](https://user-images.githubusercontent.com/10854571/59591181-d5cad700-90ed-11e9-9639-5721b4358dc9.png)

Thank you.

BR
Dante

**Comment by georged** [comment]
@dantedantas 

`statuscode` is an optionset field, it would have the name and the value separately. `ownerid`, on the other hand, is a lookup field so they are different datatypes - that's why you're seeing different results. 

Perhaps, it'd be helpful to get a better understanding of CRM datatypes and how they're returned from a query by using xrmtoolbox.com (look for fetchxml builder plugin). On php side of things we don't do any magic, we process returned XML so understanding what is being returned is a key to the data access.

HTH
George
