### ISSUE TITLE
How can I use it with Dynamics 365 SOAP Service

### ISSUE THREAD

**Issue by smk85** [AlexaCRM/php-crm-toolkit#93]
Hi, 
I was wondering if it is possible to use this library with dynamics 365 that has a customized soap service. 
I was given a wsdl url and i need to connect to it via PHP.
Using SOAP Client seems to only give me a forbidden error each time I try to call the method, but i am able to getFunctions(). 
I was hoping this toolkit could help me connect and call methods. but not sure how to use it. Could I have working example? I keep getting problem with nullloger when i try to implement it. so maybe i am doing something wrong.

**Comment by georged** [comment]
Hi @smk85 

I'm not sure what do you mean by customized soap service - it's not something that Dynamics 365 supports. It's just standard SOAP interface. Can you share wsdl url?

You're getting forbidden error probably because you're not authenticated. Have you created a configuration to connect to Dynamics 365 as per the samples? E.g.

`
$options = [
    'serverUrl' => 'https://org.crmN.dynamics.com',
    'username' => 'portal@org.onmicrosoft.com',
    'password' => 'portalPassword',
    'authMode' => 'OnlineFederation',
];

$serviceSettings = new Settings( $options );
$service = new OrganizationService( $serviceSettings );
`

Thanks
George

**Comment by smk85** [comment]
Yes. 
But it is not working right. I think because it is a CRM and mine is a sandbox url, but even though I add the crm region it does not get the right URL for the service. 
My wsdl url is something like this

https://somename.sandbox.ax.dynamics.com/soap/services/serviceName?wsdl

And what I know is that it is behind a windows authentication.

**Comment by georged** [comment]
That's Dynamics 365 Finance & Operations (aka AX). We only work with Dynamics 365 Customer Engagement (aka CRM)

Sorry for the confusion
